from check_catalog import CheckDefinition

CHECKS = (
    CheckDefinition("OD-AC-001", "OneDrive", ("conditional access alignment", "onedrive conditional access alignment")),
    CheckDefinition("OD-AC-002", "OneDrive", ("device compliance alignment", "onedrive device compliance alignment")),
    CheckDefinition("OD-AC-003", "OneDrive", ("download restrictions", "onedrive download restrictions")),
    CheckDefinition("OD-AC-004", "OneDrive", ("mfa access alignment", "onedrive mfa access alignment")),
    CheckDefinition("OD-AC-005", "OneDrive", ("unmanaged device access", "onedrive unmanaged device access")),
    CheckDefinition("OD-COMP-001", "OneDrive", ("dlp coverage", "onedrive dlp coverage")),
    CheckDefinition("OD-COMP-002", "OneDrive", ("information barriers integration", "onedrive information barriers integration")),
    CheckDefinition("OD-COMP-003", "OneDrive", ("records management integration", "onedrive records management integration")),
    CheckDefinition("OD-COMP-004", "OneDrive", ("retention policy coverage", "onedrive retention policy coverage")),
    CheckDefinition("OD-COMP-005", "OneDrive", ("sensitivity label coverage", "onedrive sensitivity label coverage")),
    CheckDefinition("OD-COMP-006", "OneDrive", ("ediscovery readiness", "onedrive ediscovery readiness")),
    CheckDefinition("OD-CM-001", "OneDrive", ("version history configuration", "onedrive version history configuration")),
    CheckDefinition("OD-GOV-001", "OneDrive", ("onedrive governance summary", "governance summary")),
    CheckDefinition("OD-LIC-001", "OneDrive", ("onedrive license coverage", "license coverage")),
    CheckDefinition("OD-LC-001", "OneDrive", ("deleted user retention coverage", "deleted user retention")),
    CheckDefinition("OD-LC-002", "OneDrive", ("former employee onedrives", "former employee onedrive sites")),
    CheckDefinition("OD-LC-003", "OneDrive", ("inactive onedrive sites", "inactive sites")),
    CheckDefinition("OD-LC-004", "OneDrive", ("onedrive retention", "retention")),
    CheckDefinition("OD-LC-005", "OneDrive", ("orphaned onedrive sites", "orphaned sites")),
    CheckDefinition("OD-OPS-001", "OneDrive", ("known folder move adoption", "kfm adoption")),
    CheckDefinition("OD-OPS-002", "OneDrive", ("onedrive admin notifications", "admin notifications")),
    CheckDefinition("OD-OPS-003", "OneDrive", ("onedrive service health readiness", "service health readiness")),
    CheckDefinition("OD-OPS-004", "OneDrive", ("onedrive usage trends", "usage trends")),
    CheckDefinition("OD-OPS-005", "OneDrive", ("sync health reporting", "onedrive sync health reporting")),
    CheckDefinition("OD-REC-001", "OneDrive", ("file restore readiness", "onedrive file restore readiness")),
    CheckDefinition("OD-REC-002", "OneDrive", ("recycle bin retention", "onedrive recycle bin retention")),
    CheckDefinition("OD-REC-003", "OneDrive", ("restore capability review", "onedrive restore capability")),
    CheckDefinition("OD-SEC-001", "OneDrive", ("app only authentication", "app-only authentication")),
    CheckDefinition("OD-SEC-002", "OneDrive", ("legacy authentication", "onedrive legacy authentication")),
    CheckDefinition("OD-SEC-003", "OneDrive", ("malware and infected file controls", "malware infected file controls")),
    CheckDefinition("OD-SEC-004", "OneDrive", ("onedrive security baseline", "security baseline")),
    CheckDefinition("OD-SEC-005", "OneDrive", ("personal vault governance", "personal vault")),
    CheckDefinition("OD-SEC-006", "OneDrive", ("ransomware recovery posture", "ransomware recovery")),
    CheckDefinition("OD-SHR-001", "OneDrive", ("anyone link exposure", "anyone links")),
    CheckDefinition("OD-SHR-002", "OneDrive", ("default sharing links", "default sharing link")),
    CheckDefinition("OD-SHR-003", "OneDrive", ("external user expiration", "guest expiration")),
    CheckDefinition("OD-SHR-004", "OneDrive", ("guest resharing", "guest resharing controls")),
    CheckDefinition("OD-SHR-005", "OneDrive", ("onedrive external sharing", "external sharing")),
    CheckDefinition("OD-SHR-006", "OneDrive", ("sharing domain restrictions", "external sharing domain restrictions")),
    CheckDefinition("OD-SITE-001", "OneDrive", ("onedrive ownership coverage", "ownership coverage")),
    CheckDefinition("OD-SITE-002", "OneDrive", ("onedrive site inventory", "site inventory")),
    CheckDefinition("OD-STOR-001", "OneDrive", ("high storage consumers", "onedrive high storage consumers")),
    CheckDefinition("OD-STOR-002", "OneDrive", ("onedrive storage defaults", "storage defaults")),
    CheckDefinition("OD-STOR-003", "OneDrive", ("storage utilization", "onedrive storage utilization")),
    CheckDefinition("OD-SYNC-001", "OneDrive", ("block sync on unmanaged devices", "block sync unmanaged devices")),
    CheckDefinition("OD-SYNC-002", "OneDrive", ("files on demand configuration", "files on-demand configuration")),
    CheckDefinition("OD-SYNC-003", "OneDrive", ("known folder move readiness", "kfm readiness")),
    CheckDefinition("OD-SYNC-004", "OneDrive", ("sync app version governance", "sync version governance")),
    CheckDefinition("OD-SYNC-005", "OneDrive", ("sync client restrictions", "onedrive sync client restrictions")),
    CheckDefinition("OD-TEN-001", "OneDrive", ("onedrive tenant configuration", "tenant configuration")),
)
