from check_catalog import CheckDefinition

CHECKS = (
    CheckDefinition("INTUNE-ADM-001", "Microsoft Intune", ("role based access control", "role-based access control", "intune rbac")),
    CheckDefinition("INTUNE-ADM-002", "Microsoft Intune", ("scope tags", "intune scope tags")),
    CheckDefinition("INTUNE-APP-001", "Microsoft Intune", ("app configuration policies", "application configuration policies")),
    CheckDefinition("INTUNE-APP-002", "Microsoft Intune", ("app protection policies", "application protection policies")),
    CheckDefinition("INTUNE-APP-003", "Microsoft Intune", ("failed application deployments", "failed app deployments")),
    CheckDefinition("INTUNE-APP-004", "Microsoft Intune", ("managed app inventory", "managed application inventory")),
    CheckDefinition("INTUNE-APP-005", "Microsoft Intune", ("required application deployment", "required app deployment")),
    CheckDefinition("INTUNE-CERT-001", "Microsoft Intune", ("certificate profiles", "intune certificate profiles")),
    CheckDefinition("INTUNE-CERT-002", "Microsoft Intune", ("scep pkcs configuration", "scep/pkcs configuration", "scep and pkcs configuration")),
    CheckDefinition("INTUNE-COMP-001", "Microsoft Intune", ("android compliance policies",)),
    CheckDefinition("INTUNE-COMP-002", "Microsoft Intune", ("compliance grace periods",)),
    CheckDefinition("INTUNE-COMP-003", "Microsoft Intune", ("conditional access integration", "intune conditional access integration")),
    CheckDefinition("INTUNE-COMP-004", "Microsoft Intune", ("noncompliant device actions", "actions for noncompliance")),
    CheckDefinition("INTUNE-COMP-005", "Microsoft Intune", ("windows compliance policies",)),
    CheckDefinition("INTUNE-COMP-006", "Microsoft Intune", ("ios compliance policies", "iphone ipad compliance policies")),
    CheckDefinition("INTUNE-COMP-007", "Microsoft Intune", ("macos compliance policies",)),
    CheckDefinition("INTUNE-CFG-001", "Microsoft Intune", ("device configuration profiles", "configuration profiles")),
    CheckDefinition("INTUNE-CFG-002", "Microsoft Intune", ("security baselines", "intune security baselines")),
    CheckDefinition("INTUNE-DEV-001", "Microsoft Intune", ("device inventory", "intune device inventory")),
    CheckDefinition("INTUNE-DEV-002", "Microsoft Intune", ("devices without primary user", "no primary user devices")),
    CheckDefinition("INTUNE-DEV-003", "Microsoft Intune", ("duplicate device records", "duplicate devices")),
    CheckDefinition("INTUNE-DEV-004", "Microsoft Intune", ("noncompliant devices",)),
    CheckDefinition("INTUNE-DEV-005", "Microsoft Intune", ("stale managed devices", "stale devices")),
    CheckDefinition("INTUNE-ENR-001", "Microsoft Intune", ("android enrollment",)),
    CheckDefinition("INTUNE-ENR-002", "Microsoft Intune", ("apple enrollment",)),
    CheckDefinition("INTUNE-ENR-003", "Microsoft Intune", ("corporate device identifiers",)),
    CheckDefinition("INTUNE-ENR-004", "Microsoft Intune", ("enrollment device limits",)),
    CheckDefinition("INTUNE-ENR-005", "Microsoft Intune", ("enrollment restrictions",)),
    CheckDefinition("INTUNE-ENR-006", "Microsoft Intune", ("windows enrollment",)),
    CheckDefinition("INTUNE-GOV-001", "Microsoft Intune", ("intune governance summary", "governance summary")),
    CheckDefinition("INTUNE-NET-001", "Microsoft Intune", ("vpn profiles", "intune vpn profiles")),
    CheckDefinition("INTUNE-NET-002", "Microsoft Intune", ("wifi profiles", "wi-fi profiles", "intune wifi profiles")),
    CheckDefinition("INTUNE-SEC-001", "Microsoft Intune", ("account protection policies",)),
    CheckDefinition("INTUNE-SEC-002", "Microsoft Intune", ("antivirus policies",)),
    CheckDefinition("INTUNE-SEC-003", "Microsoft Intune", ("application control policies", "app control policies")),
    CheckDefinition("INTUNE-SEC-004", "Microsoft Intune", ("attack surface reduction", "asr policies")),
    CheckDefinition("INTUNE-SEC-005", "Microsoft Intune", ("bitlocker configuration", "bitlocker")),
    CheckDefinition("INTUNE-SEC-006", "Microsoft Intune", ("disk encryption policies",)),
    CheckDefinition("INTUNE-SEC-007", "Microsoft Intune", ("endpoint security policies",)),
    CheckDefinition("INTUNE-SEC-008", "Microsoft Intune", ("filevault configuration", "filevault")),
    CheckDefinition("INTUNE-SEC-009", "Microsoft Intune", ("firewall policies",)),
    CheckDefinition("INTUNE-SEC-010", "Microsoft Intune", ("intune security baseline summary", "security baseline summary")),
    CheckDefinition("INTUNE-SEC-011", "Microsoft Intune", ("local admin password solution", "laps", "windows laps")),
    CheckDefinition("INTUNE-TEN-001", "Microsoft Intune", ("intune tenant configuration", "tenant configuration")),
    CheckDefinition("INTUNE-TEN-002", "Microsoft Intune", ("mdm authority", "mobile device management authority")),
    CheckDefinition("INTUNE-WIN-001", "Microsoft Intune", ("autopilot deployment profiles",)),
    CheckDefinition("INTUNE-WIN-002", "Microsoft Intune", ("autopilot esp configuration", "enrollment status page configuration")),
    CheckDefinition("INTUNE-WIN-003", "Microsoft Intune", ("feature update policies",)),
    CheckDefinition("INTUNE-WIN-004", "Microsoft Intune", ("quality update policies",)),
    CheckDefinition("INTUNE-WIN-005", "Microsoft Intune", ("windows update rings", "update rings")),
)
