from check_catalog import CheckDefinition

CHECKS = (
    CheckDefinition("TEAMS-APP-001", "Microsoft Teams", ("custom app upload", "teams custom app upload")),
    CheckDefinition("TEAMS-APP-002", "Microsoft Teams", ("teams app inventory", "app inventory")),
    CheckDefinition("TEAMS-APP-003", "Microsoft Teams", ("teams app permission policies", "app permission policies")),
    CheckDefinition("TEAMS-APP-004", "Microsoft Teams", ("teams app setup policies", "app setup policies")),
    CheckDefinition("TEAMS-APP-005", "Microsoft Teams", ("third party app access", "third-party app access")),
    CheckDefinition("TEAMS-CH-001", "Microsoft Teams", ("channel ownership and membership", "channel ownership membership")),
    CheckDefinition("TEAMS-CH-002", "Microsoft Teams", ("external shared channel access", "shared channel external access")),
    CheckDefinition("TEAMS-CH-003", "Microsoft Teams", ("private channel inventory", "private channels")),
    CheckDefinition("TEAMS-CH-004", "Microsoft Teams", ("shared channel inventory", "shared channels")),
    CheckDefinition("TEAMS-COMP-001", "Microsoft Teams", ("information barriers for teams", "teams information barriers")),
    CheckDefinition("TEAMS-COMP-002", "Microsoft Teams", ("teams dlp integration", "dlp integration")),
    CheckDefinition("TEAMS-COMP-003", "Microsoft Teams", ("teams retention integration", "retention integration")),
    CheckDefinition("TEAMS-COMP-004", "Microsoft Teams", ("teams sensitivity labels", "sensitivity labels")),
    CheckDefinition("TEAMS-COMP-005", "Microsoft Teams", ("teams ediscovery readiness", "ediscovery readiness")),
    CheckDefinition("TEAMS-DEV-001", "Microsoft Teams", ("teams device compliance", "device compliance")),
    CheckDefinition("TEAMS-DEV-002", "Microsoft Teams", ("teams devices inventory", "teams device inventory")),
    CheckDefinition("TEAMS-DEV-003", "Microsoft Teams", ("teams phone device configuration", "teams phone devices")),
    CheckDefinition("TEAMS-DEV-004", "Microsoft Teams", ("teams rooms configuration", "teams rooms")),
    CheckDefinition("TEAMS-EXT-001", "Microsoft Teams", ("external access federation", "teams external federation")),
    CheckDefinition("TEAMS-GOV-001", "Microsoft Teams", ("teams governance summary", "governance summary")),
    CheckDefinition("TEAMS-GUEST-001", "Microsoft Teams", ("guest access configuration", "teams guest access")),
    CheckDefinition("TEAMS-GUEST-002", "Microsoft Teams", ("guest calling controls", "teams guest calling")),
    CheckDefinition("TEAMS-GUEST-003", "Microsoft Teams", ("guest meeting controls", "teams guest meeting controls")),
    CheckDefinition("TEAMS-GUEST-004", "Microsoft Teams", ("guest messaging controls", "teams guest messaging controls")),
    CheckDefinition("TEAMS-LC-001", "Microsoft Teams", ("archived teams", "teams archive")),
    CheckDefinition("TEAMS-LC-002", "Microsoft Teams", ("inactive teams", "inactive microsoft teams")),
    CheckDefinition("TEAMS-LC-003", "Microsoft Teams", ("teams expiration alignment", "team expiration alignment")),
    CheckDefinition("TEAMS-MTG-001", "Microsoft Teams", ("anonymous meeting join", "anonymous join")),
    CheckDefinition("TEAMS-MTG-002", "Microsoft Teams", ("external meeting access", "external access to meetings")),
    CheckDefinition("TEAMS-MTG-003", "Microsoft Teams", ("meeting app permissions", "teams meeting app permissions")),
    CheckDefinition("TEAMS-MTG-004", "Microsoft Teams", ("meeting chat controls", "teams meeting chat controls")),
    CheckDefinition("TEAMS-MTG-005", "Microsoft Teams", ("meeting lobby configuration", "teams meeting lobby")),
    CheckDefinition("TEAMS-MTG-006", "Microsoft Teams", ("meeting recording controls", "teams meeting recording controls")),
    CheckDefinition("TEAMS-MTG-007", "Microsoft Teams", ("meeting transcription controls", "teams transcription controls")),
    CheckDefinition("TEAMS-MTG-008", "Microsoft Teams", ("teams meeting policies", "meeting policies")),
    CheckDefinition("TEAMS-MSG-001", "Microsoft Teams", ("teams messaging policies", "messaging policies")),
    CheckDefinition("TEAMS-SEC-001", "Microsoft Teams", ("teams audit configuration", "audit configuration")),
    CheckDefinition("TEAMS-SEC-002", "Microsoft Teams", ("teams security baseline", "security baseline")),
    CheckDefinition("TEAMS-TEAM-001", "Microsoft Teams", ("guest membership in teams", "team guest membership")),
    CheckDefinition("TEAMS-TEAM-002", "Microsoft Teams", ("ownerless teams", "teams without owners")),
    CheckDefinition("TEAMS-TEAM-003", "Microsoft Teams", ("single owner teams", "single-owner teams", "teams with single owner")),
    CheckDefinition("TEAMS-TEAM-004", "Microsoft Teams", ("teams ownership coverage", "team ownership coverage")),
    CheckDefinition("TEAMS-TEN-001", "Microsoft Teams", ("teams tenant configuration", "tenant configuration")),
    CheckDefinition("TEAMS-TEN-002", "Microsoft Teams", ("teams upgrade policy", "upgrade policy")),
    CheckDefinition("TEAMS-VOICE-001", "Microsoft Teams", ("teams calling policies", "calling policies")),
    CheckDefinition("TEAMS-VOICE-002", "Microsoft Teams", ("emergency calling configuration", "teams emergency calling configuration")),
    CheckDefinition("TEAMS-VOICE-003", "Microsoft Teams", ("calling plan configuration", "teams calling plan configuration")),
    CheckDefinition("TEAMS-VOICE-004", "Microsoft Teams", ("voice routing policies", "teams voice routing policies")),
    CheckDefinition("TEAMS-VOICE-005", "Microsoft Teams", ("dial plan configuration", "teams dial plan configuration")),
    CheckDefinition("TEAMS-VOICE-006", "Microsoft Teams", ("caller id policies", "teams caller id policies")),
)
