from check_catalog import CheckDefinition

CHECKS = (
    CheckDefinition("PUR-ADM-001", "Microsoft Purview", ("privileged purview roles", "purview privileged roles")),
    CheckDefinition("PUR-ADM-002", "Microsoft Purview", ("role group membership", "purview role group membership")),
    CheckDefinition("PUR-ALT-001", "Microsoft Purview", ("purview alerts and incidents", "alerts and incidents")),
    CheckDefinition("PUR-AUD-001", "Microsoft Purview", ("audit configuration", "purview audit configuration")),
    CheckDefinition("PUR-AUD-002", "Microsoft Purview", ("audit retention policies",)),
    CheckDefinition("PUR-AUD-003", "Microsoft Purview", ("audit search readiness",)),
    CheckDefinition("PUR-COMM-001", "Microsoft Purview", ("communication compliance alerts",)),
    CheckDefinition("PUR-COMM-002", "Microsoft Purview", ("communication compliance policies",)),
    CheckDefinition("PUR-CM-001", "Microsoft Purview", ("compliance manager assessments",)),
    CheckDefinition("PUR-CM-002", "Microsoft Purview", ("compliance score", "purview compliance score")),
    CheckDefinition("PUR-CLASS-001", "Microsoft Purview", ("custom sensitive information types", "custom sit")),
    CheckDefinition("PUR-CLASS-002", "Microsoft Purview", ("data classification coverage",)),
    CheckDefinition("PUR-CLASS-003", "Microsoft Purview", ("data explorer readiness",)),
    CheckDefinition("PUR-CLASS-004", "Microsoft Purview", ("exact data match configuration", "edm configuration")),
    CheckDefinition("PUR-CLASS-005", "Microsoft Purview", ("sensitive information types", "sensitive info types")),
    CheckDefinition("PUR-CLASS-006", "Microsoft Purview", ("trainable classifiers",)),
    CheckDefinition("PUR-LC-001", "Microsoft Purview", ("adaptive policy scopes",)),
    CheckDefinition("PUR-LC-002", "Microsoft Purview", ("retention label publishing",)),
    CheckDefinition("PUR-LC-003", "Microsoft Purview", ("retention labels",)),
    CheckDefinition("PUR-LC-004", "Microsoft Purview", ("retention policies",)),
    CheckDefinition("PUR-GOV-001", "Microsoft Purview", ("purview governance summary", "governance summary")),
    CheckDefinition("PUR-GOV-002", "Microsoft Purview", ("purview security baseline", "security baseline")),
    CheckDefinition("PUR-IB-001", "Microsoft Purview", ("information barriers policies", "information barrier policies")),
    CheckDefinition("PUR-IB-002", "Microsoft Purview", ("information barriers segments", "information barrier segments")),
    CheckDefinition("PUR-IP-001", "Microsoft Purview", ("auto labeling policies", "auto-labeling policies")),
    CheckDefinition("PUR-IP-002", "Microsoft Purview", ("container sensitivity labels",)),
    CheckDefinition("PUR-IP-003", "Microsoft Purview", ("default sensitivity labels",)),
    CheckDefinition("PUR-IP-004", "Microsoft Purview", ("encryption settings", "purview encryption settings")),
    CheckDefinition("PUR-IP-005", "Microsoft Purview", ("sensitivity label publishing",)),
    CheckDefinition("PUR-IP-006", "Microsoft Purview", ("sensitivity labels",)),
    CheckDefinition("PUR-IR-001", "Microsoft Purview", ("insider risk alerts",)),
    CheckDefinition("PUR-IR-002", "Microsoft Purview", ("insider risk policies",)),
    CheckDefinition("PUR-REC-001", "Microsoft Purview", ("disposition review",)),
    CheckDefinition("PUR-REC-002", "Microsoft Purview", ("event based retention", "event-based retention")),
    CheckDefinition("PUR-REC-003", "Microsoft Purview", ("record labels",)),
    CheckDefinition("PUR-REC-004", "Microsoft Purview", ("records management configuration",)),
    CheckDefinition("PUR-REC-005", "Microsoft Purview", ("regulatory record labels",)),
    CheckDefinition("PUR-EDISC-001", "Microsoft Purview", ("content search readiness",)),
    CheckDefinition("PUR-EDISC-002", "Microsoft Purview", ("ediscovery cases", "e-discovery cases")),
    CheckDefinition("PUR-EDISC-003", "Microsoft Purview", ("ediscovery holds", "e-discovery holds")),
    CheckDefinition("PUR-TEN-001", "Microsoft Purview", ("purview tenant configuration", "tenant configuration")),
)
