from check_catalog import CheckDefinition

# Exchange Online checks emitted by the current 50-control assessment.
# The base catalog already contains the core mail-flow/security mappings;
# this extension fills the remaining canonical titles used by production CSVs.
CHECKS = (
    CheckDefinition("EXO-TP-001", "Exchange Online", ("anti-phish policies", "anti phish policies", "anti-phishing policies")),
    CheckDefinition("EXO-TP-002", "Exchange Online", ("safe links policies", "safe links policy")),
    CheckDefinition("EXO-TP-003", "Exchange Online", ("safe attachments policies", "safe attachments policy")),
    CheckDefinition("EXO-TP-004", "Exchange Online", ("quarantine policies", "quarantine policy")),
    CheckDefinition("EXO-TP-005", "Exchange Online", ("outbound spam policies", "outbound spam policy")),
    CheckDefinition("EXO-TP-006", "Exchange Online", ("connection filter policy", "connection filter policies")),
    CheckDefinition("EXO-TP-007", "Exchange Online", ("malware filter policies", "malware filter policy", "anti-malware policies")),
    CheckDefinition("EXO-TP-008", "Exchange Online", ("tenant allow block list", "tenant allow/block list", "tenant allow block list entries")),
    CheckDefinition("EXO-COMP-001", "Exchange Online", ("journaling rules", "journal rules")),
    CheckDefinition("EXO-COMP-002", "Exchange Online", ("retention policies", "exchange retention policies")),
    CheckDefinition("EXO-COMP-003", "Exchange Online", ("retention tags", "exchange retention tags")),
    CheckDefinition("EXO-COMP-004", "Exchange Online", ("litigation hold coverage", "litigation hold")),
    CheckDefinition("EXO-COMP-005", "Exchange Online", ("in-place hold coverage", "in place hold coverage", "in-place holds")),
    CheckDefinition("EXO-COMP-006", "Exchange Online", ("mailbox retention assignments", "retention policy assignments")),
    CheckDefinition("EXO-MBX-001", "Exchange Online", ("recoverable items quota", "recoverable items quotas")),
    CheckDefinition("EXO-MBX-002", "Exchange Online", ("archive mailbox coverage", "archive mailboxes", "online archive coverage")),
    CheckDefinition("EXO-MBX-003", "Exchange Online", ("mailbox forwarding rules", "mailbox forwarding rule")),
    CheckDefinition("EXO-MBX-004", "Exchange Online", ("shared mailbox sign-in risk", "shared mailbox signin risk", "shared mailbox sign in risk")),
    CheckDefinition("EXO-OPS-001", "Exchange Online", ("mailbox size utilization", "mailbox size usage")),
    CheckDefinition("EXO-OPS-002", "Exchange Online", ("inactive mailboxes", "inactive mailbox inventory")),
    CheckDefinition("EXO-OPS-003", "Exchange Online", ("distribution group governance", "distribution groups")),
    CheckDefinition("EXO-OPS-004", "Exchange Online", ("dynamic distribution groups", "dynamic distribution group governance")),
    CheckDefinition("EXO-OPS-005", "Exchange Online", ("mail-enabled security groups", "mail enabled security groups")),
    CheckDefinition("EXO-OPS-006", "Exchange Online", ("public folders", "exchange public folders")),
    CheckDefinition("EXO-OPS-007", "Exchange Online", ("mail contacts", "exchange mail contacts")),
    CheckDefinition("EXO-OPS-008", "Exchange Online", ("mail users", "exchange mail users")),
    CheckDefinition("EXO-MF-008", "Exchange Online", ("moderated recipients", "recipient moderation")),
    CheckDefinition("EXO-MF-009", "Exchange Online", ("message size limits", "message size limit")),
    CheckDefinition("EXO-MF-010", "Exchange Online", ("external sender identification", "external sender identification configuration")),
    CheckDefinition("EXO-OPS-009", "Exchange Online", ("focused inbox configuration", "focused inbox")),
    CheckDefinition("EXO-AUTH-001", "Exchange Online", ("modern authentication readiness", "modern authentication")),
    CheckDefinition("EXO-AUTH-002", "Exchange Online", ("legacy protocol exposure", "legacy protocols", "legacy authentication protocol exposure")),
    CheckDefinition("EXO-AUTH-003", "Exchange Online", ("oauth configuration", "oauth", "exchange oauth configuration")),
    CheckDefinition("EXO-MF-011", "Exchange Online", ("transport configuration", "exchange transport configuration")),
    CheckDefinition("EXO-GOV-001", "Exchange Online", ("organization configuration", "exchange organization configuration")),
    CheckDefinition("EXO-GOV-002", "Exchange Online", ("administrative role groups", "exchange role groups", "admin role groups")),
    CheckDefinition("EXO-GOV-003", "Exchange Online", ("exchange governance summary", "exchange online governance summary")),
)
