from check_catalog import CheckDefinition

CHECKS = (
    CheckDefinition("DEF-ALERT-001", "Microsoft Defender", ("alert policies", "defender alert policies")),
    CheckDefinition("DEF-ALERT-002", "Microsoft Defender", ("incident queue health", "defender incident queue health")),
    CheckDefinition("DEF-ALERT-003", "Microsoft Defender", ("suppression rules", "alert suppression rules")),
    CheckDefinition("DEF-ALERT-004", "Microsoft Defender", ("unresolved high severity incidents", "high severity incidents")),
    CheckDefinition("DEF-AUTO-001", "Microsoft Defender", ("air pending actions", "automated investigation pending actions")),
    CheckDefinition("DEF-AUTO-002", "Microsoft Defender", ("automated investigation configuration", "air configuration")),
    CheckDefinition("DEF-CLOUD-001", "Microsoft Defender", ("cloud discovery coverage", "defender cloud discovery")),
    CheckDefinition("DEF-CLOUD-002", "Microsoft Defender", ("defender for cloud apps integration", "cloud apps integration")),
    CheckDefinition("DEF-CLOUD-003", "Microsoft Defender", ("oauth app risk", "oauth application risk")),
    CheckDefinition("DEF-CLOUD-004", "Microsoft Defender", ("unsanctioned app activity", "unsanctioned applications")),
    CheckDefinition("DEF-END-001", "Microsoft Defender", ("attack surface reduction", "asr")),
    CheckDefinition("DEF-END-002", "Microsoft Defender", ("cloud delivered protection", "cloud-delivered protection")),
    CheckDefinition("DEF-END-003", "Microsoft Defender", ("defender for endpoint onboarding", "endpoint onboarding")),
    CheckDefinition("DEF-END-004", "Microsoft Defender", ("device isolation readiness", "endpoint device isolation")),
    CheckDefinition("DEF-END-005", "Microsoft Defender", ("edr in block mode", "endpoint detection response block mode")),
    CheckDefinition("DEF-END-006", "Microsoft Defender", ("endpoint sensor health", "sensor health")),
    CheckDefinition("DEF-END-007", "Microsoft Defender", ("endpoint tamper protection", "tamper protection")),
    CheckDefinition("DEF-END-008", "Microsoft Defender", ("network protection", "defender network protection")),
    CheckDefinition("DEF-END-009", "Microsoft Defender", ("web protection", "defender web protection")),
    CheckDefinition("DEF-GOV-001", "Microsoft Defender", ("defender governance summary", "governance summary")),
    CheckDefinition("DEF-ID-001", "Microsoft Defender", ("compromised user signals", "identity compromised user signals")),
    CheckDefinition("DEF-ID-002", "Microsoft Defender", ("defender for identity sensor health", "identity sensor health")),
    CheckDefinition("DEF-ID-003", "Microsoft Defender", ("identity alerts", "defender identity alerts")),
    CheckDefinition("DEF-ID-004", "Microsoft Defender", ("lateral movement paths", "identity lateral movement paths")),
    CheckDefinition("DEF-INT-001", "Microsoft Defender", ("defender integration coverage", "integration coverage")),
    CheckDefinition("DEF-LIC-001", "Microsoft Defender", ("defender for office 365 licensing", "defender office 365 licensing")),
    CheckDefinition("DEF-POST-001", "Microsoft Defender", ("defender security baseline", "security baseline")),
    CheckDefinition("DEF-POST-002", "Microsoft Defender", ("microsoft secure score", "secure score")),
    CheckDefinition("DEF-POST-003", "Microsoft Defender", ("secure score improvement actions", "improvement actions")),
    CheckDefinition("DEF-TEN-001", "Microsoft Defender", ("defender tenant configuration", "tenant configuration")),
    CheckDefinition("DEF-HUNT-001", "Microsoft Defender", ("advanced hunting readiness", "advanced hunting")),
    CheckDefinition("DEF-HUNT-002", "Microsoft Defender", ("custom detection rules", "custom detections")),
    CheckDefinition("DEF-HUNT-003", "Microsoft Defender", ("threat analytics access", "threat analytics")),
    CheckDefinition("DEF-TI-001", "Microsoft Defender", ("threat intelligence indicators", "threat indicators")),
)
