[CmdletBinding()]
param(
    [string]$Destination = (Join-Path $PSScriptRoot 'dist'),
    [switch]$IncludeOptionalPnP
)

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$ConfigPath = Join-Path $Root 'TenantIQ.json'
$ValidatorPath = Join-Path $Root 'Test-TenantIQReleasePackage.ps1'

if (-not (Test-Path $ConfigPath)) {
    throw "TenantIQ.json was not found at $ConfigPath"
}

if (-not (Test-Path $ValidatorPath)) {
    throw "Release package validator was not found at $ValidatorPath"
}

$Config = Get-Content -Path $ConfigPath -Raw | ConvertFrom-Json
$Version = if ($Config.Version) { [string]$Config.Version } else { '0.0.0' }
$PackageName = "TenantIQ-v$Version"
$PackageRoot = Join-Path $Destination $PackageName
$ZipPath = Join-Path $Destination "$PackageName.zip"

$RequiredFiles = @(
    'Start-TenantIQ.ps1',
    'TenantIQ.ps1',
    'TenantIQ.json',
    'TenantIQ-License.template.json',
    'TenantIQ-License-Public.pem',
    'Install-TenantIQPrerequisites.ps1',
    'Get-TenantIQVersion.ps1',
    'Get-TenantIQLicenseStatus.ps1',
    'Test-TenantIQReleasePackage.ps1',
    'QUICKSTART.md',
    'CUSTOMER-README.md',
    'CHANGELOG.md'
)

$RequiredDirectories = @(
    '00 Runtime',
    '01 Framework',
    '02 Health Checks',
    '03 Reports',
    '04 Scripts',
    '05 Templates',
    '07 Assets',
    '10 Modules'
)

$BuildCommit = $null
try {
    if (Get-Command git -ErrorAction SilentlyContinue) {
        $BuildCommit = (& git -C $Root rev-parse --short=12 HEAD 2>$null).Trim()
    }
}
catch {}

Write-Host ''
Write-Host 'TenantIQ Customer Package Builder' -ForegroundColor Cyan
Write-Host '=================================' -ForegroundColor Cyan
Write-Host ("Version      : {0}" -f $Version)
Write-Host ("Channel      : {0}" -f [string]$Config.ReleaseChannel)
Write-Host ("Build Commit : {0}" -f $(if ($BuildCommit) { $BuildCommit } else { 'Unavailable' }))
Write-Host ("Destination  : {0}" -f $Destination)
Write-Host ''

foreach ($File in $RequiredFiles) {
    if (-not (Test-Path (Join-Path $Root $File))) {
        if ($File -eq 'TenantIQ-License-Public.pem') {
            throw 'TenantIQ signing public key is not configured. Run .\Initialize-TenantIQLicenseKeys.ps1 once, then commit only TenantIQ-License-Public.pem.'
        }
        throw "Required package file is missing: $File"
    }
}

foreach ($Directory in $RequiredDirectories) {
    if (-not (Test-Path (Join-Path $Root $Directory))) {
        throw "Required package directory is missing: $Directory"
    }
}

if (Test-Path $PackageRoot) {
    Remove-Item -Path $PackageRoot -Recurse -Force
}
if (Test-Path $ZipPath) {
    Remove-Item -Path $ZipPath -Force
}
if (Test-Path "$ZipPath.sha256") {
    Remove-Item -Path "$ZipPath.sha256" -Force
}

New-Item -Path $PackageRoot -ItemType Directory -Force | Out-Null

foreach ($File in $RequiredFiles) {
    Copy-Item -Path (Join-Path $Root $File) -Destination (Join-Path $PackageRoot $File) -Force
}

foreach ($Directory in $RequiredDirectories) {
    Copy-Item -Path (Join-Path $Root $Directory) -Destination (Join-Path $PackageRoot $Directory) -Recurse -Force
}

New-Item -Path (Join-Path $PackageRoot '06 Output') -ItemType Directory -Force | Out-Null
Set-Content -Path (Join-Path $PackageRoot '06 Output\README.txt') -Encoding UTF8 -Value @'
TenantIQ assessment output is written to this directory.

Workload CSV files and Portfolio Report files generated by TenantIQ will appear here.
Do not combine workload CSV files from different Microsoft 365 tenants into one Portfolio Report.
'@

$PatternsToRemove = @(
    '*.analysis.json',
    '*.log',
    '*.tmp',
    '*.bak',
    '*.old',
    '*.orig',
    '*~'
)
foreach ($Pattern in $PatternsToRemove) {
    Get-ChildItem -Path $PackageRoot -Recurse -File -Filter $Pattern -ErrorAction SilentlyContinue |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

$PackagedLicense = Join-Path $PackageRoot 'TenantIQ-License.json'
if (Test-Path $PackagedLicense) {
    Remove-Item -Path $PackagedLicense -Force
}

Get-ChildItem -Path $PackageRoot -Recurse -Force -Directory -Filter '.git' -ErrorAction SilentlyContinue |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

$rsaPublic = [System.Security.Cryptography.RSA]::Create()
try {
    $rsaPublic.ImportFromPem((Get-Content -Path (Join-Path $Root 'TenantIQ-License-Public.pem') -Raw))
    $PublicBytes = $rsaPublic.ExportSubjectPublicKeyInfo()
    $LicenseKeyId = [Convert]::ToHexString([System.Security.Cryptography.SHA256]::HashData($PublicBytes)).Substring(0,16)
}
finally { $rsaPublic.Dispose() }

$BuildInfo = [ordered]@{
    Product              = 'TenantIQ'
    Version              = $Version
    BuiltAt              = (Get-Date).ToString('o')
    ReleaseChannel       = [string]$Config.ReleaseChannel
    PackageType          = 'Customer'
    BuildCommit          = $BuildCommit
    Controls             = 416
    Workloads            = 8
    MinimumPowerShell    = '7.0'
    LicensingMode        = 'SignedLicenseVerification'
    LicenseKeyId         = $LicenseKeyId
    LicenseEnforcement   = $false
    OptionalPnPRequested = [bool]$IncludeOptionalPnP
}
$BuildInfo | ConvertTo-Json -Depth 4 | Set-Content -Path (Join-Path $PackageRoot 'PACKAGE-INFO.json') -Encoding UTF8

$ManifestPath = Join-Path $PackageRoot 'PACKAGE-SHA256.txt'
$ManifestRows = Get-ChildItem -Path $PackageRoot -Recurse -File |
    Where-Object { $_.FullName -ne $ManifestPath } |
    Sort-Object FullName |
    ForEach-Object {
        $Relative = $_.FullName.Substring($PackageRoot.Length).TrimStart('\','/')
        $Hash = (Get-FileHash -Path $_.FullName -Algorithm SHA256).Hash
        '{0}  {1}' -f $Hash,$Relative
    }
$ManifestRows | Set-Content -Path $ManifestPath -Encoding UTF8

Compress-Archive -Path (Join-Path $PackageRoot '*') -DestinationPath $ZipPath -CompressionLevel Optimal -Force
$ZipHash = (Get-FileHash -Path $ZipPath -Algorithm SHA256).Hash
$ZipHashPath = "$ZipPath.sha256"
'{0}  {1}' -f $ZipHash,(Split-Path $ZipPath -Leaf) | Set-Content -Path $ZipHashPath -Encoding UTF8

Write-Host ''
Write-Host 'Running release package validation...' -ForegroundColor Cyan
$Validation = & $ValidatorPath -PackageRoot $PackageRoot -ZipPath $ZipPath
if (-not $Validation.Ready) {
    throw 'TenantIQ customer package failed release validation.'
}

Write-Host ''
Write-Host '[OK] Customer package created and validated.' -ForegroundColor Green
Write-Host ("Folder      : {0}" -f $PackageRoot) -ForegroundColor Cyan
Write-Host ("ZIP         : {0}" -f $ZipPath) -ForegroundColor Cyan
Write-Host ("ZIP SHA256  : {0}" -f $ZipHash) -ForegroundColor Cyan
Write-Host ("License Key : {0}" -f $LicenseKeyId) -ForegroundColor Cyan
Write-Host ("Validation  : RELEASE READY ({0} checks passed)" -f $Validation.Passed) -ForegroundColor Green
Write-Host ''
Write-Host 'Customer support/version commands:' -ForegroundColor Yellow
Write-Host '  .\Get-TenantIQVersion.ps1'
Write-Host '  .\Get-TenantIQLicenseStatus.ps1'
Write-Host '  .\Test-TenantIQReleasePackage.ps1 -PackageRoot <folder> -ZipPath <zip>'
Write-Host ''
Write-Host 'Customer first-run commands:' -ForegroundColor Yellow
Write-Host '  .\Install-TenantIQPrerequisites.ps1'
Write-Host '  .\Start-TenantIQ.ps1'

[pscustomobject]@{
    Version        = $Version
    ReleaseChannel = [string]$Config.ReleaseChannel
    BuildCommit    = $BuildCommit
    PackageRoot    = $PackageRoot
    ZipPath        = $ZipPath
    ZipSha256      = $ZipHash
    ZipHashPath    = $ZipHashPath
    LicensingMode  = 'SignedLicenseVerification'
    LicenseKeyId   = $LicenseKeyId
    ReleaseReady   = $true
    ValidationPass = $Validation.Passed
}
