$TenantIQSharePointHealthChecks = @(

    @{ Name="Tenant Configuration"; Number=1; Status="Implemented"; Enabled=$true; Category="Tenant"; Severity="High"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews tenant-wide SharePoint Online configuration, sharing defaults, legacy authentication, access controls, storage, OneDrive retention, and external-user settings."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Tenant\Test-TenantConfiguration.ps1" }
    @{ Name="External Sharing Configuration"; Number=2; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online external sharing, anonymous links, guest expiration, resharing, domain restrictions, and OneDrive sharing controls."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-ExternalSharing.ps1" }
    @{ Name="Site Inventory"; Number=3; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Inventories SharePoint Online site collections and reviews lock state, sharing capability, storage utilization, and site activity."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-SiteInventory.ps1" }
    @{ Name="Site-Level External Sharing"; Number=4; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews effective external sharing configuration across SharePoint Online site collections, including anonymous sharing, default links, expiration settings, and domain restrictions."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-SiteExternalSharing.ps1" }
    @{ Name="Anonymous Link Exposure"; Number=5; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online sites that permit Anyone links and evaluates anonymous-link defaults, permissions, and expiration overrides."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-AnonymousLinkExposure.ps1" }
    @{ Name="Sharing Domain Restrictions"; Number=6; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Low"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews tenant and site-level external sharing domain restrictions, including allow lists, block lists, and configuration consistency."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-SharingDomainRestrictions.ps1" }
    @{ Name="External User Expiration Policy"; Number=7; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online external-user expiration controls, including the tenant-wide expiration policy and site-level overrides."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-ExternalUserExpiration.ps1" }
    @{ Name="Default Sharing Link Configuration"; Number=8; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online tenant and site default sharing-link scope and permission settings."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-DefaultSharingLinkConfiguration.ps1" }
    @{ Name="Guest Resharing Controls"; Number=9; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online guest resharing controls, externally shareable sites, anonymous-capable sites, and security-group restrictions for external sharing."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-GuestResharingControls.ps1" }
    @{ Name="External Sharing Security Groups"; Number=10; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Low"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews Microsoft Entra security-group allow lists used to restrict which users can share SharePoint Online content externally."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-ExternalSharingSecurityGroups.ps1" }
    @{ Name="Unmanaged Device Access"; Number=11; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Medium"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online access controls for unmanaged devices, including full access, limited web access, download restrictions, and blocking."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-UnmanagedDeviceAccess.ps1" }
    @{ Name="Idle Session Sign-Out"; Number=12; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Medium"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online and OneDrive browser idle-session sign-out configuration, including warning and automatic sign-out intervals."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-IdleSessionSignOut.ps1" }
    @{ Name="Legacy Authentication"; Number=13; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="High"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online legacy authentication settings and identifies enabled non-modern authentication paths."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-LegacyAuthentication.ps1" }
    @{ Name="Conditional Access Integration"; Number=14; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Medium"; EstimatedTime="5 sec"; Version="1.0"; Description="Evaluates SharePoint Online access-control settings used with Microsoft Entra Conditional Access, including unmanaged-device access, limited access, downloads, and editing."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-ConditionalAccessIntegration.ps1" }
    @{ Name="App-Only Authentication"; Number=15; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="High"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online legacy Azure ACS app-only authentication and verifies that legacy custom app authentication is disabled."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-AppOnlyAuthentication.ps1" }
    @{ Name="Site Access Restrictions"; Number=16; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Low"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online Restricted Access Control configuration, including tenant enablement, site restrictions, control groups, delegation, and sharing behavior."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-SiteAccessRestrictions.ps1" }
    @{ Name="Site Creation Controls"; Number=17; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="Low"; EstimatedTime="5 sec"; Version="1.0"; Description="Reviews SharePoint Online self-service site creation, Start-A-Site availability, and site provisioning governance controls."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-SiteCreationControls.ps1" }
    @{ Name="Site Storage Management"; Number=18; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews SharePoint Online tenant storage capacity and site-level storage utilization."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-SiteStorageManagement.ps1" }
    @{ Name="Site Lock State"; Number=19; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint Online site collections for ReadOnly, NoAccess, and unexpected lock states."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-SiteLockState.ps1" }
    @{ Name="Site Collection Administrator Coverage"; Number=20; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="High"; EstimatedTime="15 sec"; Version="1.0"; Description="Reviews human site collection administrator coverage for traditional SharePoint sites while excluding Microsoft 365 Group-connected, Teams channel, and system sites from traditional SCA scoring."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-SiteCollectionAdministratorCoverage.ps1" }
    @{ Name="Microsoft 365 Group Site Ownership"; Number=21; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="High"; EstimatedTime="20 sec"; Version="1.0"; Description="Reviews ownership of Microsoft 365 Group-connected SharePoint sites, identifies ownerless or single-owner groups, distinguishes human and non-human owners, and excludes Teams channel sites from group ownership scoring."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-M365GroupSiteOwnership.ps1" }
    @{ Name="Microsoft 365 Group Guest Membership"; Number=22; Status="Implemented"; Enabled=$true; Category="Sharing"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews guest membership in Microsoft 365 Groups associated with SharePoint sites."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sharing\Test-M365GroupGuestMembership.ps1" }
    @{ Name="Orphaned Group-Connected Sites"; Number=23; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Identifies SharePoint sites whose associated Microsoft 365 Group is missing or no longer resolvable."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-OrphanedGroupConnectedSites.ps1" }
    @{ Name="Hub Site Configuration"; Number=24; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews registered hub sites, associations, ownership, and governance configuration."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-HubSiteConfiguration.ps1" }
    @{ Name="Hub Site Association Coverage"; Number=25; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Low"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews site collections for hub association coverage and identifies standalone sites requiring governance review."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-HubSiteAssociationCoverage.ps1" }
    @{ Name="Site Sensitivity Labels"; Number=26; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews sensitivity label assignment across SharePoint sites and Microsoft 365 Group-connected sites."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-SiteSensitivityLabels.ps1" }
    @{ Name="Unlabeled Externally Shared Sites"; Number=27; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Identifies externally shareable SharePoint sites without sensitivity labels."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-UnlabeledExternallySharedSites.ps1" }
    @{ Name="Site Classification"; Number=28; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="Low"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint site classification values and missing classification metadata."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-SiteClassification.ps1" }
    @{ Name="Inactive Sites"; Number=29; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Identifies SharePoint sites with extended periods of inactivity for lifecycle review."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-InactiveSites.ps1" }
    @{ Name="Unused Group-Connected Sites"; Number=30; Status="Implemented"; Enabled=$true; Category="Sites"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Identifies Microsoft 365 Group-connected sites with low or stale activity."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Sites\Test-UnusedGroupConnectedSites.ps1" }
    @{ Name="Deleted Site Retention"; Number=31; Status="Implemented"; Enabled=$true; Category="Lifecycle"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews deleted-site retention and recycle-bin lifecycle posture."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Lifecycle\Test-DeletedSiteRetention.ps1" }
    @{ Name="Site Lifecycle Policies"; Number=32; Status="Implemented"; Enabled=$true; Category="Lifecycle"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews available site lifecycle and inactive-site governance controls."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Lifecycle\Test-SiteLifecyclePolicies.ps1" }
    @{ Name="Version History Limits"; Number=33; Status="Implemented"; Enabled=$true; Category="Content Management"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews tenant and site version history limit configuration."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Content Management\Test-VersionHistoryLimits.ps1" }
    @{ Name="Automatic Version Trimming"; Number=34; Status="Implemented"; Enabled=$true; Category="Content Management"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews automatic version expiration and trimming configuration."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Content Management\Test-AutomaticVersionTrimming.ps1" }
    @{ Name="Large List Threshold Risk"; Number=35; Status="Implemented"; Enabled=$true; Category="Content Management"; Severity="Low"; EstimatedTime="10 sec"; Version="1.0"; Description="Identifies sites and lists that may require large-list governance review."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Content Management\Test-LargeListThresholdRisk.ps1" }
    @{ Name="Site Templates and Customization"; Number=36; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="Low"; EstimatedTime="10 sec"; Version="1.0"; Description="Inventories site templates and identifies legacy or highly customized site types."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-SiteTemplatesAndCustomization.ps1" }
    @{ Name="Custom Script Settings"; Number=37; Status="Implemented"; Enabled=$true; Category="Security"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews tenant and site custom-script controls and legacy customization exposure."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Security\Test-CustomScriptSettings.ps1" }
    @{ Name="App Catalog Configuration"; Number=38; Status="Implemented"; Enabled=$true; Category="Applications"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews tenant app catalog availability and governance configuration."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Applications\Test-AppCatalogConfiguration.ps1" }
    @{ Name="Tenant App Catalog Apps"; Number=39; Status="Implemented"; Enabled=$true; Category="Applications"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Inventories tenant app catalog packages and highlights governance or trust concerns."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Applications\Test-TenantAppCatalogApps.ps1" }
    @{ Name="Site Collection App Catalogs"; Number=40; Status="Implemented"; Enabled=$true; Category="Applications"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews site collection app catalogs and decentralized app deployment exposure."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Applications\Test-SiteCollectionAppCatalogs.ps1" }
    @{ Name="SharePoint Add-In Retirement Readiness"; Number=41; Status="Implemented"; Enabled=$true; Category="Applications"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews legacy SharePoint Add-In and ACS dependency indicators for retirement readiness."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Applications\Test-AddInRetirementReadiness.ps1" }
    @{ Name="OneDrive Retention Configuration"; Number=42; Status="Implemented"; Enabled=$true; Category="OneDrive Integration"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint tenant OneDrive retention settings used after account deletion."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\OneDrive Integration\Test-OneDriveRetentionConfiguration.ps1" }
    @{ Name="OneDrive Sharing Alignment"; Number=43; Status="Implemented"; Enabled=$true; Category="OneDrive Integration"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Compares OneDrive and SharePoint sharing capabilities for governance alignment."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\OneDrive Integration\Test-OneDriveSharingAlignment.ps1" }
    @{ Name="Sync Client Restrictions"; Number=44; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews tenant controls affecting OneDrive and SharePoint sync client access."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-SyncClientRestrictions.ps1" }
    @{ Name="Domain Restricted Sync"; Number=45; Status="Implemented"; Enabled=$true; Category="Access Control"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews restrictions that limit sync to approved domains or managed devices."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Access Control\Test-DomainRestrictedSync.ps1" }
    @{ Name="Information Barriers Integration"; Number=46; Status="Implemented"; Enabled=$true; Category="Compliance"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint information barriers configuration and segment integration."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Compliance\Test-InformationBarriersIntegration.ps1" }
    @{ Name="Records Management Integration"; Number=47; Status="Implemented"; Enabled=$true; Category="Compliance"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint records-management related tenant configuration and site posture."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Compliance\Test-RecordsManagementIntegration.ps1" }
    @{ Name="Restricted Content Discovery"; Number=48; Status="Implemented"; Enabled=$true; Category="Security"; Severity="High"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews controls intended to restrict discovery or access to sensitive SharePoint sites."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Security\Test-RestrictedContentDiscovery.ps1" }
    @{ Name="Tenant CDN Configuration"; Number=49; Status="Implemented"; Enabled=$true; Category="Performance"; Severity="Low"; EstimatedTime="10 sec"; Version="1.0"; Description="Reviews SharePoint Online CDN configuration and enabled origins."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Performance\Test-TenantCDNConfiguration.ps1" }
    @{ Name="SharePoint Governance Summary"; Number=50; Status="Implemented"; Enabled=$true; Category="Governance"; Severity="Medium"; EstimatedTime="10 sec"; Version="1.0"; Description="Provides a consolidated governance summary across SharePoint tenant, sharing, site, lifecycle, and security controls."; Script="$PSScriptRoot\..\02 Health Checks\SharePoint Online\Governance\Test-SharePointGovernanceSummary.ps1" }

)
