# TenantIQ Exchange Online hardened evaluator
# Read-only evidence-backed control evaluation.

function Add-TenantIQExchangeResult {
    param([string]$Check,[string]$Category,[string]$Status,[string]$Severity,[string]$Finding,[string]$Recommendation,[double]$Duration)
    if (Get-Command New-HealthCheckResult -ErrorAction SilentlyContinue) {
        $null = New-HealthCheckResult -Check $Check -Category $Category -Status $Status -Severity $Severity -Finding $Finding -Recommendation $Recommendation -Duration $Duration
    }
    else {
        if (-not (Get-Variable ExchangeAIResults -Scope Global -ErrorAction SilentlyContinue)) { $Global:ExchangeAIResults = @() }
        $Global:ExchangeAIResults += [pscustomobject]@{Check=$Check;Category=$Category;Status=$Status;Severity=$Severity;Finding=$Finding;Recommendation=$Recommendation;Duration=$Duration}
    }
}

function Invoke-TenantIQExchangeCommand {
    param([string]$Command,[hashtable]$Parameters=@{})
    if (-not (Get-Command $Command -ErrorAction SilentlyContinue)) {
        return [pscustomobject]@{Success=$false;Items=@();Count=0;Error="Cmdlet $Command is not available in the current Exchange Online session."}
    }
    try {
        $Items = @(& $Command @Parameters -ErrorAction Stop)
        return [pscustomobject]@{Success=$true;Items=$Items;Count=$Items.Count;Error=$null}
    }
    catch {
        return [pscustomobject]@{Success=$false;Items=@();Count=0;Error=$_.Exception.Message}
    }
}

function Invoke-TenantIQExchangeHardenedCheck {
    param([Parameter(Mandatory)][string]$CheckName,[Parameter(Mandatory)][string]$Category,[Parameter(Mandatory)][string]$DeclaredSeverity)
    $sw=[Diagnostics.Stopwatch]::StartNew()
    try {
        switch ($CheckName) {
            'Anti-Phish Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-AntiPhishPolicy';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Anti-phish policy evidence unavailable: $($p.Error)" 'Review anti-phishing policy configuration in Microsoft Defender for Office 365.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'WARNING' $DeclaredSeverity 'No anti-phish policies were returned.' 'Configure anti-phishing protection if Defender for Office 365 is licensed and in scope.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) anti-phish policy object(s) were returned." 'Review impersonation protection, mailbox intelligence, and spoof settings.' $sw.Elapsed.TotalSeconds};return }
            'Safe Links Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-SafeLinksPolicy';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Safe Links evidence unavailable: $($p.Error)" 'Review Safe Links in Microsoft Defender for Office 365.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'No Safe Links policies were returned.' 'No action is required unless Defender for Office 365 is licensed and Safe Links is in scope.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) Safe Links policy object(s) were returned." 'Review click protection and policy targeting.' $sw.Elapsed.TotalSeconds};return }
            'Safe Attachments Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-SafeAttachmentPolicy';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Safe Attachments evidence unavailable: $($p.Error)" 'Review Safe Attachments in Microsoft Defender for Office 365.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'No Safe Attachments policies were returned.' 'No action is required unless Defender for Office 365 is licensed and Safe Attachments is in scope.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) Safe Attachments policy object(s) were returned." 'Review dynamic delivery/block/monitor behavior and targeting.' $sw.Elapsed.TotalSeconds};return }
            'Quarantine Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-QuarantinePolicy';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) quarantine policy object(s) were returned." 'Review administrative/user release permissions and notifications.' $sw.Elapsed.TotalSeconds}elseif($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'No custom quarantine policy objects were returned.' 'Review quarantine policy configuration if custom handling is required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Quarantine policy evidence unavailable: $($p.Error)" 'Review quarantine policy configuration in Microsoft Defender.' $sw.Elapsed.TotalSeconds};return }
            'Outbound Spam Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-HostedOutboundSpamFilterPolicy';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) outbound spam filter policy object(s) were returned." 'Review automatic forwarding and outbound recipient limits.' $sw.Elapsed.TotalSeconds}elseif($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'WARNING' $DeclaredSeverity 'No outbound spam filter policies were returned.' 'Review outbound spam controls.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Outbound spam policy evidence unavailable: $($p.Error)" 'Review outbound spam policy configuration.' $sw.Elapsed.TotalSeconds};return }
            'Connection Filter Policy' { $p=Invoke-TenantIQExchangeCommand 'Get-HostedConnectionFilterPolicy';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Connection filter evidence unavailable: $($p.Error)" 'Review connection filtering in Defender.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'WARNING' $DeclaredSeverity 'No hosted connection filter policy was returned.' 'Verify Exchange Online Protection connection filtering configuration.' $sw.Elapsed.TotalSeconds;return};$Allow=@($p.Items|ForEach-Object{@($_.IPAllowList)}|Where-Object{$_}).Count;$Block=@($p.Items|ForEach-Object{@($_.IPBlockList)}|Where-Object{$_}).Count;$Status=if($Allow -gt 20){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($p.Count) connection filter policy object(s) were returned; allow entries=$Allow; block entries=$Block." 'Review IP allow entries carefully and remove stale or overly broad exceptions.' $sw.Elapsed.TotalSeconds;return }
            'Malware Filter Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-MalwareFilterPolicy';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) malware filter policy object(s) were returned." 'Review malware response and file filtering settings.' $sw.Elapsed.TotalSeconds}elseif($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'WARNING' $DeclaredSeverity 'No malware filter policies were returned.' 'Review malware protection configuration.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Malware filter evidence unavailable: $($p.Error)" 'Review malware protection configuration.' $sw.Elapsed.TotalSeconds};return }
            'Tenant Allow Block List' { $sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'Tenant Allow/Block List is not consistently exposed through the Exchange Online PowerShell surface used by TenantIQ.' 'Review Tenant Allow/Block List entries in Microsoft Defender and remove stale exceptions.' $sw.Elapsed.TotalSeconds;return }
            'Journaling Rules' { $p=Invoke-TenantIQExchangeCommand 'Get-JournalRule';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Journaling evidence unavailable: $($p.Error)" 'Review journaling requirements.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No legacy Exchange journaling rules are configured.' 'Continue using modern compliance retention unless journaling is explicitly required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($p.Count) journaling rule object(s) were returned." 'Review whether legacy journaling is still required and migrate where appropriate.' $sw.Elapsed.TotalSeconds};return }
            'Retention Policies' { $p=Invoke-TenantIQExchangeCommand 'Get-RetentionPolicy';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) Exchange retention policy object(s) were returned." 'Review legacy MRM use alongside Purview retention.' $sw.Elapsed.TotalSeconds}elseif($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'No Exchange MRM retention policies were returned.' 'No action is required if Purview retention is authoritative.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Retention policy evidence unavailable: $($p.Error)" 'Review retention configuration.' $sw.Elapsed.TotalSeconds};return }
            'Retention Tags' { $p=Invoke-TenantIQExchangeCommand 'Get-RetentionPolicyTag';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Retention tag evidence unavailable: $($p.Error)" 'Review retention configuration.' $sw.Elapsed.TotalSeconds;return};if($p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) retention policy tag object(s) were returned." 'Review tag relevance if Exchange MRM remains in use.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'No Exchange retention policy tags were returned.' 'No action is required if Purview retention is authoritative.' $sw.Elapsed.TotalSeconds};return }
            'Litigation Hold Coverage' { $p=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('LitigationHoldEnabled','RecipientTypeDetails')};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Litigation hold evidence unavailable: $($p.Error)" 'Review hold configuration in Exchange/Purview.' $sw.Elapsed.TotalSeconds;return};$Users=@($p.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'});$Held=@($Users|Where-Object{$_.LitigationHoldEnabled -eq $true});Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($Held.Count) of $($Users.Count) user mailboxes have Litigation Hold enabled." 'Confirm legal hold scope against documented legal requirements.' $sw.Elapsed.TotalSeconds;return }
            'In-Place Hold Coverage' { $sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'Legacy In-Place Hold coverage is not reliably represented by the modern Exchange Online cmdlet surface used by TenantIQ.' 'Review active eDiscovery holds in Microsoft Purview.' $sw.Elapsed.TotalSeconds;return }
            'Mailbox Retention Assignments' { $p=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('RetentionPolicy','RecipientTypeDetails')};$sw.Stop();if($p.Success){$Users=@($p.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'});$Assigned=@($Users|Where-Object{-not [string]::IsNullOrWhiteSpace([string]$_.RetentionPolicy)});$Status=if($Users.Count -gt 0 -and $Assigned.Count -eq $Users.Count){'PASS'}else{'INFO'};Add-TenantIQExchangeResult $CheckName $Category $Status 'None' "$($Assigned.Count) of $($Users.Count) user mailboxes have an Exchange retention policy assigned." 'Use this as context when determining whether Exchange MRM is still operationally relevant.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mailbox retention assignment evidence unavailable: $($p.Error)" 'Review mailbox retention configuration.' $sw.Elapsed.TotalSeconds};return }
            'Recoverable Items Quota' { $p=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('RecoverableItemsQuota','RecipientTypeDetails')};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Recoverable items quota evidence unavailable: $($p.Error)" 'Review mailbox quota configuration.' $sw.Elapsed.TotalSeconds;return};$Users=@($p.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'});$Missing=@($Users|Where-Object{[string]::IsNullOrWhiteSpace([string]$_.RecoverableItemsQuota)});$Status=if($Missing.Count -eq 0){'PASS'}else{'WARNING'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($Users.Count) user mailbox(es) were reviewed; $($Missing.Count) have no recoverable-items quota value returned." 'Review quota exceptions for litigation/retention-heavy mailboxes.' $sw.Elapsed.TotalSeconds;return }
            'Archive Mailbox Coverage' { $p=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('ArchiveStatus','RecipientTypeDetails')};$sw.Stop();if($p.Success){$Users=@($p.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'});$Archived=@($Users|Where-Object{[string]$_.ArchiveStatus -eq 'Active'});Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($Archived.Count) of $($Users.Count) user mailboxes have an active archive." 'Confirm archive enablement aligns with retention and mailbox growth requirements.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Archive evidence unavailable: $($p.Error)" 'Review archive configuration.' $sw.Elapsed.TotalSeconds};return }
            'Mailbox Forwarding Rules' {
                $m=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('PrimarySmtpAddress','RecipientTypeDetails')}
                if(-not $m.Success){$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mailbox inventory unavailable for inbox-rule forwarding review: $($m.Error)" 'Review mailbox forwarding rules manually for high-risk accounts.' $sw.Elapsed.TotalSeconds;return}
                $External=0;$Internal=0;$Errors=0;$Scanned=0
                foreach($mbx in @($m.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'})){
                    try{$rules=@(Get-InboxRule -Mailbox $mbx.PrimarySmtpAddress -ErrorAction Stop);$Scanned++;foreach($r in $rules){$targets=@($r.ForwardTo)+@($r.RedirectTo)+@($r.ForwardAsAttachmentTo);foreach($t in @($targets|Where-Object{$_})){$s=[string]$t;if($s -match '@' -and $s -notmatch '(?i)@[^\s]+\.mail\.onmicrosoft\.com$'){$External++}else{$Internal++}}}}catch{$Errors++}
                }
                $sw.Stop();$Status=if($External -gt 0){'WARNING'}elseif($Errors -eq 0){'PASS'}else{'INFO'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "Inbox rules were reviewed for $Scanned user mailbox(es). External forwarding/redirect targets=$External; internal targets=$Internal; mailbox query errors=$Errors." 'Remove unauthorized external forwarding rules and investigate compromised or stale mailboxes.' $sw.Elapsed.TotalSeconds;return
            }
            'Shared Mailbox Sign-In Risk' {
                $p=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('RecipientTypeDetails','ExternalDirectoryObjectId','PrimarySmtpAddress')}
                if(-not $p.Success){$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Shared mailbox evidence unavailable: $($p.Error)" 'Review shared mailbox account posture.' $sw.Elapsed.TotalSeconds;return}
                $Shared=@($p.Items|Where-Object{$_.RecipientTypeDetails -eq 'SharedMailbox'});if($Shared.Count -eq 0){$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No shared mailboxes were identified.' 'No action required.' $sw.Elapsed.TotalSeconds;return}
                $Enabled=0;$Unknown=0;if(Get-Command Get-MgUser -ErrorAction SilentlyContinue){foreach($mbx in $Shared){try{$u=Get-MgUser -UserId $mbx.ExternalDirectoryObjectId -Property AccountEnabled -ErrorAction Stop;if($u.AccountEnabled -eq $true){$Enabled++}}catch{$Unknown++}}}else{$Unknown=$Shared.Count}
                $sw.Stop();$Status=if($Enabled -gt 0){'WARNING'}elseif($Unknown -eq 0){'PASS'}else{'INFO'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($Shared.Count) shared mailbox(es) identified; Entra sign-in enabled=$Enabled; account state unknown=$Unknown." 'Disable direct sign-in for shared mailbox identities unless explicitly required.' $sw.Elapsed.TotalSeconds;return
            }
            'Mailbox Size Utilization' {
                $m=Invoke-TenantIQExchangeCommand 'Get-EXOMailbox' @{ResultSize='Unlimited';Properties=@('PrimarySmtpAddress','RecipientTypeDetails','ProhibitSendReceiveQuota')}
                if(-not $m.Success){$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mailbox inventory unavailable: $($m.Error)" 'Review mailbox capacity and quota exceptions.' $sw.Elapsed.TotalSeconds;return}
                $Users=@($m.Items|Where-Object{$_.RecipientTypeDetails -eq 'UserMailbox'});$Errors=0;$Scanned=0;foreach($mbx in $Users){try{$null=Get-EXOMailboxStatistics -Identity $mbx.PrimarySmtpAddress -Properties TotalItemSize -ErrorAction Stop;$Scanned++}catch{$Errors++}}
                $sw.Stop();$Status=if($Errors -eq 0){'PASS'}else{'INFO'};Add-TenantIQExchangeResult $CheckName $Category $Status 'None' "Mailbox statistics were collected for $Scanned of $($Users.Count) user mailbox(es); query errors=$Errors." 'Review mailboxes approaching quota and investigate abnormal growth trends.' $sw.Elapsed.TotalSeconds;return
            }
            'Inactive Mailboxes' { $p=Invoke-TenantIQExchangeCommand 'Get-Mailbox' @{InactiveMailboxOnly=$true;ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Inactive mailbox evidence unavailable: $($p.Error)" 'Review inactive mailboxes in Purview/Exchange.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No inactive mailboxes were returned.' 'No action required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'WARNING' $DeclaredSeverity "$($p.Count) inactive mailbox object(s) were returned." 'Review inactive mailbox retention, hold requirements, ownership, and deletion governance.' $sw.Elapsed.TotalSeconds};return }
            'Distribution Group Governance' { $p=Invoke-TenantIQExchangeCommand 'Get-DistributionGroup' @{ResultSize='Unlimited'};$sw.Stop();if($p.Success){$NoOwner=@($p.Items|Where-Object{@($_.ManagedBy).Count -eq 0});$Status=if($NoOwner.Count -gt 0){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($p.Count) distribution group(s) were returned; $($NoOwner.Count) have no listed owner." 'Assign accountable owners and review stale groups.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Distribution group evidence unavailable: $($p.Error)" 'Review distribution group governance.' $sw.Elapsed.TotalSeconds};return }
            'Dynamic Distribution Groups' { $p=Invoke-TenantIQExchangeCommand 'Get-DynamicDistributionGroup' @{ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Dynamic group evidence unavailable: $($p.Error)" 'Review dynamic distribution groups.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No dynamic distribution groups were returned.' 'No action required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($p.Count) dynamic distribution group(s) were returned." 'Review recipient filters, ownership, and business justification for dynamic groups.' $sw.Elapsed.TotalSeconds};return }
            'Mail-Enabled Security Groups' { $p=Invoke-TenantIQExchangeCommand 'Get-DistributionGroup' @{ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mail-enabled security group evidence unavailable: $($p.Error)" 'Review mail-enabled security groups.' $sw.Elapsed.TotalSeconds;return};$Sec=@($p.Items|Where-Object{[string]$_.RecipientTypeDetails -match 'MailUniversalSecurityGroup'});$NoOwner=@($Sec|Where-Object{@($_.ManagedBy).Count -eq 0});$Status=if($NoOwner.Count -gt 0){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($Sec.Count) mail-enabled security group(s) were identified; $($NoOwner.Count) have no listed owner." 'Assign ownership and review continued need and delivery restrictions.' $sw.Elapsed.TotalSeconds;return }
            'Public Folders' { $org=Invoke-TenantIQExchangeCommand 'Get-OrganizationConfig';if(-not $org.Success -or $org.Count -eq 0){$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Public folder organization context unavailable: $($org.Error)" 'Review public folder usage.' $sw.Elapsed.TotalSeconds;return};$orgName=[string](($org.Items|Select-Object -First 1).Name);$p=Invoke-TenantIQExchangeCommand 'Get-PublicFolder' @{Recurse=$true;ResultSize='Unlimited';Organization=$orgName};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Public folder evidence unavailable after organization-qualified query: $($p.Error)" 'Review public folder usage and Exchange organization context.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No public folder objects were returned.' 'No action required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($p.Count) public folder object(s) were returned." 'Review legacy public-folder dependencies, permissions, and ownership.' $sw.Elapsed.TotalSeconds};return }
            'Mail Contacts' { $p=Invoke-TenantIQExchangeCommand 'Get-MailContact' @{ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mail contact evidence unavailable: $($p.Error)" 'Review mail contacts.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No mail contacts were returned.' 'No action required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($p.Count) mail contact object(s) were returned." 'Review external targets, ownership, and stale contacts.' $sw.Elapsed.TotalSeconds};return }
            'Mail Users' { $p=Invoke-TenantIQExchangeCommand 'Get-MailUser' @{ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Mail user evidence unavailable: $($p.Error)" 'Review mail users.' $sw.Elapsed.TotalSeconds;return};if($p.Count -eq 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'No mail users were returned.' 'No action required.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "$($p.Count) mail user object(s) were returned." 'Review stale mail users, external routing targets, and hybrid dependencies.' $sw.Elapsed.TotalSeconds};return }
            'Moderated Recipients' { $p=Invoke-TenantIQExchangeCommand 'Get-Recipient' @{ResultSize='Unlimited'};$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Moderation evidence unavailable: $($p.Error)" 'Review moderated recipients.' $sw.Elapsed.TotalSeconds;return};$Mod=@($p.Items|Where-Object{$_.ModerationEnabled -eq $true});$Status=if($Mod.Count -eq 0){'PASS'}else{'INFO'};Add-TenantIQExchangeResult $CheckName $Category $Status 'None' "$($Mod.Count) moderated recipient object(s) were identified from $($p.Count) recipients." 'Review moderation ownership and necessity.' $sw.Elapsed.TotalSeconds;return }
            'Message Size Limits' { $p=Invoke-TenantIQExchangeCommand 'Get-TransportConfig';$sw.Stop();if($p.Success -and $p.Count -gt 0){$o=$p.Items|Select-Object -First 1;Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "Transport limits returned. MaxReceiveSize=$($o.MaxReceiveSize); MaxSendSize=$($o.MaxSendSize)." 'Review limits against business requirements and avoid unnecessarily high values.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Transport limit evidence unavailable: $($p.Error)" 'Review transport configuration.' $sw.Elapsed.TotalSeconds};return }
            'External Sender Identification' { $p=Invoke-TenantIQExchangeCommand 'Get-ExternalInOutlook';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "External sender identification evidence unavailable: $($p.Error)" 'Review external sender identification settings.' $sw.Elapsed.TotalSeconds;return};$Disabled=@($p.Items|Where-Object{$_.Enabled -eq $false}).Count;$Status=if($Disabled -gt 0){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($p.Count) external-in-Outlook configuration object(s) were returned; disabled entries=$Disabled." 'Review exceptions and ensure external sender identification is not broadly suppressed.' $sw.Elapsed.TotalSeconds;return }
            'Focused Inbox Configuration' { $sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'Focused Inbox is primarily a user-experience setting and is not scored as a security control.' 'No action is required unless organizational standards mandate a specific setting.' $sw.Elapsed.TotalSeconds;return }
            'Modern Authentication Readiness' { $p=Invoke-TenantIQExchangeCommand 'Get-OrganizationConfig';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'Exchange organization configuration was retrieved successfully; modern Exchange Online connectivity is available.' 'Continue restricting legacy authentication through Entra Conditional Access and Exchange protocol controls.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'NOT EVALUATED' 'None' "Organization configuration unavailable: $($p.Error)" 'Confirm Exchange Online connectivity.' $sw.Elapsed.TotalSeconds};return }
            'Legacy Protocol Exposure' { $p=Invoke-TenantIQExchangeCommand 'Get-CASMailbox' @{ResultSize='Unlimited'};$sw.Stop();if($p.Success){$Pop=@($p.Items|Where-Object{$_.PopEnabled -eq $true}).Count;$Imap=@($p.Items|Where-Object{$_.ImapEnabled -eq $true}).Count;$Smtp=@($p.Items|Where-Object{$_.SmtpClientAuthenticationDisabled -eq $false}).Count;$Risk=$Pop+$Imap+$Smtp;$Status=if($Risk -gt 0){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "Legacy protocol indicators: POP enabled=$Pop; IMAP enabled=$Imap; SMTP AUTH explicitly enabled=$Smtp." 'Disable unused legacy protocols and enforce modern authentication.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Legacy protocol evidence unavailable: $($p.Error)" 'Review mailbox protocol exposure.' $sw.Elapsed.TotalSeconds};return }
            'OAuth Configuration' { $p=Invoke-TenantIQExchangeCommand 'Get-AuthConfig';$sw.Stop();if($p.Success -and $p.Count -gt 0){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' "$($p.Count) Exchange AuthConfig object(s) were returned." 'Review OAuth certificate lifecycle and hybrid requirements where applicable.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "OAuth configuration evidence unavailable or empty: $($p.Error)" 'Review OAuth configuration.' $sw.Elapsed.TotalSeconds};return }
            'Transport Configuration' { $p=Invoke-TenantIQExchangeCommand 'Get-TransportConfig';$sw.Stop();if($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'Exchange transport configuration was retrieved successfully.' 'Review transport-wide settings periodically.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'NOT EVALUATED' 'None' "Transport configuration unavailable: $($p.Error)" 'Confirm Exchange Online connectivity.' $sw.Elapsed.TotalSeconds};return }
            'Organization Configuration' { $p=Invoke-TenantIQExchangeCommand 'Get-OrganizationConfig';$sw.Stop();if($p.Success){Add-TenantIQExchangeResult $CheckName $Category 'PASS' 'None' 'Exchange organization configuration was retrieved successfully.' 'Use the individual Exchange controls as the authoritative findings.' $sw.Elapsed.TotalSeconds}else{Add-TenantIQExchangeResult $CheckName $Category 'NOT EVALUATED' 'None' "Organization configuration unavailable: $($p.Error)" 'Confirm Exchange Online connectivity.' $sw.Elapsed.TotalSeconds};return }
            'Administrative Role Groups' { $p=Invoke-TenantIQExchangeCommand 'Get-RoleGroup';$sw.Stop();if(-not $p.Success){Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' "Role group evidence unavailable: $($p.Error)" 'Review Exchange administrative role assignments.' $sw.Elapsed.TotalSeconds;return};$NoMembers=0;foreach($rg in $p.Items){try{$m=@(Get-RoleGroupMember -Identity $rg.Identity -ErrorAction Stop);if($m.Count -eq 0){$NoMembers++}}catch{}};$Status=if($NoMembers -gt 0){'WARNING'}else{'PASS'};$Sev=if($Status -eq 'WARNING'){$DeclaredSeverity}else{'None'};Add-TenantIQExchangeResult $CheckName $Category $Status $Sev "$($p.Count) Exchange role group object(s) were returned; $NoMembers have no direct members." 'Review privileged role-group membership and least privilege.' $sw.Elapsed.TotalSeconds;return }
            'Exchange Governance Summary' { $sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'INFO' 'None' 'This aggregate Exchange governance control is informational and does not double-score detailed findings.' 'Use the preceding Exchange controls as the authoritative evidence.' $sw.Elapsed.TotalSeconds;return }
            default { $sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'NOT EVALUATED' 'None' "$CheckName does not yet have a dedicated Exchange evaluator mapping." 'Add a read-only evidence source before scoring this control.' $sw.Elapsed.TotalSeconds;return }
        }
    }
    catch {$sw.Stop();Add-TenantIQExchangeResult $CheckName $Category 'NOT EVALUATED' 'None' "$CheckName could not be evaluated: $($_.Exception.Message)" 'Resolve Exchange Online connectivity or permission issues and rerun.' $sw.Elapsed.TotalSeconds}
}
